name: "Groundwater 2 MQTT"
description: "Scrape ground water info from the web"
version: "1.0.3"
slug: "groundwater2mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  mqtt_server: "server.local"
  mqtt_port: 1883
  mqtt_user: "username"
  mqtt_password: "password"
  mqtt_prefix: "mqtt/prefix"
  url: "https://dummy.url"
  id: "MyID-123A"
schema:
  mqtt_server: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: password
  mqtt_prefix: str
  url: str
  id: str
